services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROME_DRIVER
        value: /usr/lib/chromium-browser/chromedriver
    apt:
      packages:
        - google-chrome-stable
        - chromium-chromedriver
